=== nicolasebastianelli/WebTech_Programming/02_TecWeb_parser/Lettera.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">	
	<xs:element name="lettera">
		<xs:complexType>
			<xs:all>
				<xs:element name="mittente" type="xs:string"/>
				<xs:element name="data" type="xs:date"/>
				<xs:element name="destinatario" type="xs:string"/>
				<xs:element name="oggetto" type="xs:string"/>
				<xs:element name="saluto" type="xs:string"/>
				<xs:element name="corpo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="paragrafo" maxOccurs="unbounded" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="chiusura" type="xs:string"/>
				<xs:element name="firma" type="xs:string"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nicolasebastianelli/WebTech_Programming/02_TecWeb_parser/Lettera.xml
<?xml version="1.0"?>
<lettera xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Lettera.xsd">
	<mittente>Nicola</mittente>
	<destinatario>Filippo</destinatario>	
	<data>2017-03-27</data>
	<oggetto>Festa</oggetto>
	<saluto>Caro Filippo</saluto>
	<corpo>
		<paragrafo>vieni gioved√¨ alla festa</paragrafo>
		<paragrafo>ci divertiamo</paragrafo>
	</corpo>
	<chiusura>Fammi sapere</chiusura>
	<firma>Nicola</firma>	
</lettera>
